server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: bookstore
  datasource:
    url: jdbc:mysql://localhost:3307/bookstore
    username: bookuser
    password: P@ssw0rdB00k
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      encoding: UTF-8
  cache:
    type: redis
  data:
    redis:
      port: 6379
